// web/src/components/react/accordion-events.tsx
import type { CollectionEntry } from 'astro:content'

import { Accordion } from '@base-ui/react/accordion'
import ChevronDown from '~icons/lucide/chevron-down'

import type { LanguageKeys } from '@/i18n'

import { formatDate } from '@/lib/format-date'
import { siteConfig } from '@/site.config'

interface Props {
  items: CollectionEntry<'event'>[]
  lang: LanguageKeys
}

const AccordionEvents = ({ items, lang }: Props) => (
  <Accordion.Root className="w-full">
    {items.map(({ data }, index) => (
      <Accordion.Item
        key={data.title}
        value={data.title}
        className="border-b border-foreground/15"
      >
        <Accordion.Header render={<div />} className="flex">
          <Accordion.Trigger className="group w-full py-6 text-left transition-opacity hover:opacity-50 focus-visible:ring-2 focus-visible:ring-foreground focus-visible:outline-none md:py-7">
            <div className="grid grid-cols-12 items-start gap-x-6 gap-y-3">
              <p className="col-span-2 text-xs font-medium tracking-[0.18em] text-foreground/40 tabular-nums cap-trim md:col-span-1">
                {String(index + 1).padStart(2, '0')}
              </p>
              <p className="col-span-9 text-xs font-medium tracking-[0.18em] text-foreground/40 uppercase tabular-nums cap-trim md:col-span-2">
                {data.dates
                  .map((date) =>
                    formatDate(date, lang, {
                      day: 'numeric',
                      month: 'short',
                      timeZone: siteConfig.timeZone,
                      year: 'numeric',
                    })
                  )
                  .join(' & ')}
              </p>
              <div className="col-span-1 flex justify-end md:order-last md:col-start-12">
                <ChevronDown className="size-5 shrink-0 transition-transform duration-300 ease-out group-data-[panel-open]:rotate-180" />
              </div>
              <h3 className="col-span-10 col-start-3 text-xl font-normal tracking-tight text-balance cap-trim md:col-span-8 md:col-start-4 md:text-2xl lg:text-3xl">
                {data.title}
              </h3>
            </div>
          </Accordion.Trigger>
        </Accordion.Header>
        <Accordion.Panel className="h-[var(--accordion-panel-height)] overflow-hidden transition-[height] duration-200 ease-out data-[ending-style]:h-0 data-[starting-style]:h-0">
          <div className="grid grid-cols-12 gap-x-6 pb-8 md:pb-10">
            <p className="col-span-10 col-start-3 max-w-[60ch] text-base leading-relaxed text-pretty text-foreground/70 md:col-span-8 md:col-start-4 md:text-lg">
              {data.description}
            </p>
          </div>
        </Accordion.Panel>
      </Accordion.Item>
    ))}
  </Accordion.Root>
)

export default AccordionEvents

// web/src/components/vue/AccordionEvents.vue
<script lang="ts">
import type { CollectionEntry } from 'astro:content'
import type { AccordionRootEmits, AccordionRootProps } from 'reka-ui'

import type { LanguageKeys } from '@/i18n'
import { cn } from '@/lib/utils'
</script>

<script setup lang="ts" generic="T extends EventItem">
import { reactivePick } from '@vueuse/core'
import {
  AccordionContent,
  AccordionHeader,
  AccordionItem,
  AccordionRoot,
  AccordionTrigger,
  useForwardPropsEmits,
} from 'reka-ui'
import { computed } from 'vue'
import ChevronDown from '~icons/lucide/chevron-down'

import { useFormatDate } from '@/composables/useFormatDate'

type EventItem = CollectionEntry<'event'>


export interface AccordionProps<T extends EventItem = EventItem> extends Pick<
  AccordionRootProps,
  | 'collapsible'
  | 'defaultValue'
  | 'modelValue'
  | 'type'
  | 'disabled'
  | 'unmountOnHide'
> {
  items: T[]
  lang: LanguageKeys
}


const props = withDefaults(defineProps<AccordionProps<T>>(), {
  collapsible: true,
  type: 'single',
  unmountOnHide: false,
})
const emits = defineEmits<AccordionRootEmits>()


const rootProps = useForwardPropsEmits(
  reactivePick(
    props,
    'collapsible',
    'defaultValue',
    'disabled',
    'modelValue',
    'unmountOnHide'
  ),
  emits
)


const datesString = computed(() =>
  props.items.map(({ data: { dates } }) =>
    dates
      .map(
        (date) =>
          useFormatDate(date, props.lang, {
            day: 'numeric',
            month: 'short',
            year: 'numeric',
          }).formattedDate.value
      )
      .join(' & ')
  )
)
</script>

<template>
  <AccordionRoot v-bind="rootProps" :type="type" class="w-full">
    <AccordionItem
      v-for="(item, index) in props.items"
      :key="item.data.title"
      :value="item.data.title"
      class="border-b border-border-dark last:border-0"
    >
      <AccordionHeader as="div" class="flex">
        <AccordionTrigger
          :class="
            cn(
              `group w-full py-8 text-left transition-opacity hover:opacity-50`,
              {
                'md:pb-12': index === 0,
                'md:py-12': index > 0,
              }
            )
          "
        >
          <div class="grid grid-cols-12 items-start gap-6">
            <span
              class="col-span-3 mt-1.5 font-mono text-xs font-semibold tracking-widest uppercase opacity-50 md:col-span-3"
            >
              {{ datesString[index] }}
            </span>
            <div class="col-span-8 md:col-span-8">
              <h3
                class="text-3xl font-medium tracking-tight text-balance md:text-4xl lg:text-5xl"
              >
                {{ item.data.title }}
              </h3>
            </div>
            <div class="col-span-1 flex justify-end">
              <ChevronDown
                class="ms-auto size-6 shrink-0 transition-transform duration-300 ease-out group-data-[state=open]:rotate-180"
              />
            </div>
          </div>
        </AccordionTrigger>
      </AccordionHeader>

      <AccordionContent
        class="overflow-hidden focus:outline-none data-[state=closed]:animate-[accordion-up_200ms_ease-out] data-[state=open]:animate-[accordion-down_200ms_ease-out]"
      >
        <div class="grid grid-cols-12 gap-6 pb-12">
          <div class="col-span-12 md:col-span-8 md:col-start-4">
            <p class="text-xl leading-relaxed opacity-70">
              {{ item.data.description }}
            </p>
          </div>
        </div>
      </AccordionContent>
    </AccordionItem>
  </AccordionRoot>
</template>
