// src/components/MobileNavigation.vue
<script lang="ts" setup>
import type { LanguageKeys } from '@/i18n'
import { DialogClose, DialogContent, DialogDescription, DialogOverlay, DialogPortal, DialogRoot, DialogTitle, DialogTrigger, VisuallyHidden } from 'reka-ui'
import Languages from '~icons/lucide/languages'
import Mail from '~icons/lucide/mail'
import Menu from '~icons/lucide/menu'
import X from '~icons/lucide/x'
import { useTranslations } from '@/i18n'
import { siteConfig } from '@/site.config'
import LinkLocal from './LinkLocal.vue'

const { lang } = defineProps<{
  lang: LanguageKeys
}>()

const { navigation, socialMediaLinks, email } = siteConfig
const t = useTranslations(lang)
</script>

<template>
  <DialogRoot>
    <DialogTrigger
      aria-label="Open menu"
      class="transition-opacity hover:opacity-50 md:hidden"
    >
      <Menu class="size-5" stroke-width="{1.5}" />
    </DialogTrigger>
    <DialogPortal>
      <DialogOverlay
        class="
          fixed inset-0 z-50 bg-black/80
          data-[state=closed]:animate-out data-[state=closed]:fade-out-0
          data-[state=open]:animate-in data-[state=open]:fade-in-0
        "
      />
      <DialogContent
        class="
          fixed inset-0 z-50 bg-background duration-200
          data-[state=closed]:animate-out data-[state=closed]:fade-out-0
          data-[state=open]:animate-in data-[state=open]:fade-in-0
        "
      >
        <VisuallyHidden>
          <DialogTitle>Mobile navigation menu</DialogTitle>
          <DialogDescription>
            Navigate to different sections of the website
          </DialogDescription>
        </VisuallyHidden>
        <div class="flex h-full flex-col">
          <div
            class="
              flex items-center justify-between border-b border-border px-6 py-8
            "
          >
            <slot name="logo" />
            <DialogClose aria-label="Close" as-child>
              <button
                aria-label="Close menu" class="
                  transition-opacity
                  hover:opacity-50
                "
              >
                <X class="size-6" :stroke-width="1.5" />
              </button>
            </DialogClose>
          </div>
          <div class="flex-1 overflow-y-auto">
            <div class="grid h-full grid-cols-12 gap-0">
              <DialogClose as-child>
                <LinkLocal
                  :href="navigation[0]!.to"
                  class="
                    group col-span-12 flex flex-col justify-between border-b
                    border-border p-6 transition-colors
                    hover:bg-foreground/5
                  "
                >
                  <span
                    class="
                      text-xs font-medium tracking-widest uppercase opacity-20
                    "
                  >01</span>
                  <div>
                    <h2
                      class="
                        text-5xl font-light tracking-tight transition-transform
                        group-hover:translate-x-2
                      "
                    >
                      {{ t(`nav.${navigation[0]!.code}`) }}
                    </h2>
                  </div>
                </LinkLocal>
              </DialogClose>
              <DialogClose as-child>
                <LinkLocal
                  :href="navigation[1]!.to"
                  class="
                    group relative col-span-7 flex flex-col justify-between
                    overflow-hidden p-6 transition-colors
                    hover:bg-foreground/5
                  "
                >
                  <div
                    class="
                      absolute top-0 right-0 h-16 w-16 translate-x-8
                      -translate-y-8 rotate-45 bg-accent-foreground/10
                    "
                  />
                  <span
                    class="
                      text-xs font-medium tracking-widest uppercase opacity-20
                    "
                  >02</span>
                  <div>
                    <h2
                      class="
                        text-4xl font-light tracking-tight transition-transform
                        group-hover:translate-x-2
                      "
                    >
                      {{ t(`nav.${navigation[1]!.code}`) }}
                    </h2>
                  </div>
                </LinkLocal>
              </DialogClose>
              <div
                class="
                  col-span-5 flex flex-col justify-between border-l
                  border-border p-6
                "
              >
                <Languages class="size-4 opacity-20" />
                <slot name="language-picker" />
              </div>

              <DialogClose as-child>
                <LinkLocal
                  :href="navigation[2]!.to"
                  class="
                    group col-span-7 flex flex-col justify-between border-t
                    border-border p-6 transition-colors
                    hover:bg-foreground/5
                  "
                >
                  <span
                    class="
                      text-xs font-medium tracking-widest uppercase opacity-20
                    "
                  >03</span>
                  <div>
                    <h2
                      class="
                        text-4xl font-light tracking-tight transition-transform
                        group-hover:translate-x-2
                      "
                    >
                      {{ t(`nav.${navigation[2]!.code}`) }}
                    </h2>
                  </div>
                </LinkLocal>
              </DialogClose>
              <div
                class="
                  relative col-span-5 flex flex-col justify-between border-t
                  border-l border-border bg-accent-foreground/5 p-6
                "
              >
                <div
                  class="
                    absolute top-6 bottom-6 left-0 w-0.5 bg-accent-foreground
                  "
                />
                <Mail class="size-4 opacity-20" />
                <div class="space-y-2">
                  <p
                    class="
                      text-xs font-medium tracking-widest uppercase opacity-40
                    "
                  >
                    {{ t('contact.email') }}
                  </p>
                  <DialogClose as-child>
                    <a
                      :href="`mailto:${email}`"
                      rel="noopener noreferrer"
                      target="_blank"
                      class="
                        block text-sm font-light break-all transition-opacity
                        hover:opacity-50
                      "
                    >
                      {{ email }}
                    </a>
                  </DialogClose>
                </div>
              </div>
              <div class="col-span-12 border-t border-border p-6">
                <div class="grid grid-cols-3 gap-6">
                  <DialogClose
                    v-for="social in socialMediaLinks"
                    :key="social.label"
                    as-child
                  >
                    <a
                      :href="social.to"
                      rel="noopener noreferrer"
                      target="_blank"
                      class="
                        flex items-center gap-2 text-xs font-medium
                        tracking-widest uppercase transition-opacity
                        hover:opacity-50
                      "
                    >
                      <span class="h-1 w-1 rounded-full bg-foreground" />
                      {{ social.label }}
                    </a>
                  </DialogClose>
                </div>
              </div>
              <slot name="footer" />
            </div>
          </div>
        </div>
      </DialogContent>
    </DialogPortal>
  </DialogRoot>
</template>

// web/src/components/react/mobile-navigation.tsx
import type { ComponentProps, ReactNode } from 'react'

import { Dialog } from '@base-ui/react/dialog'
import Menu from '~icons/lucide/menu'
import X from '~icons/lucide/x'

import type { LanguageKeys } from '@/i18n'

import { getTranslations } from '@/i18n'
import { siteConfig } from '@/site.config'

interface Props {
  lang: LanguageKeys
  languages?: ReactNode
  logo?: ReactNode
  navItems: { href: string; label: string }[]
}

const { email, socialMediaLinks } = siteConfig

const CloseLink = ({ children, ...props }: ComponentProps<'a'>) => (
  <Dialog.Close
    nativeButton={false}
    render={(closeProps) => (
      <a {...closeProps} {...props}>
        {children}
      </a>
    )}
  />
)

const MobileNavigation = ({ lang, languages, logo, navItems }: Props) => {
  const t = getTranslations(lang)

  return (
    <Dialog.Root>
      <Dialog.Trigger
        aria-label={t('nav.openMenu')}
        className="inline-flex min-h-11 items-center md:hidden"
      >
        <Menu className="size-6" strokeWidth={1.5} />
      </Dialog.Trigger>
      <Dialog.Portal>
        <Dialog.Backdrop className="fixed inset-0 z-50 bg-foreground/10" />
        <Dialog.Popup className="fixed inset-0 z-50 flex flex-col bg-background">
          <Dialog.Title className="sr-only">{t('nav.main')}</Dialog.Title>
          <Dialog.Description className="sr-only">
            {t('nav.description')}
          </Dialog.Description>
          <div className="flex shrink-0 items-center justify-between border-b border-border-dark px-6 py-8">
            {logo}
            <Dialog.Close
              aria-label={t('nav.closeMenu')}
              className="inline-flex min-h-11 items-center"
            >
              <X className="size-6" strokeWidth={1.5} />
            </Dialog.Close>
          </div>
          <div className="flex flex-1 flex-col justify-between gap-12 px-6 pt-6 pb-[max(1.5rem,env(safe-area-inset-bottom))]">
            <nav aria-label={t('nav.main')}>
              {navItems.map((item) => (
                <CloseLink
                  key={item.href}
                  href={item.href}
                  className="flex min-h-20 items-center justify-between gap-6 border-b border-border-dark py-4 text-[clamp(2.5rem,1.5rem+6vw,4rem)] leading-[1.15] tracking-[-0.035em] underline-offset-[0.15em] last:border-b-0 hover:underline hover:decoration-1"
                >
                  <span>{item.label}</span>
                  <span aria-hidden="true" className="text-2xl font-normal">
                    ↘
                  </span>
                </CloseLink>
              ))}
            </nav>
            <div>
              <dl className="grid gap-y-6 border-t border-border-dark pt-6">
                <div>
                  <dt className="text-xs font-medium tracking-[0.18em] text-foreground/40 uppercase">
                    {t('contact.email')}
                  </dt>
                  <dd>
                    <CloseLink
                      href={`mailto:${email}`}
                      className="mt-2 inline-flex min-h-11 items-center text-xl tracking-tight underline-offset-4 hover:underline"
                    >
                      {email}
                    </CloseLink>
                  </dd>
                </div>
                <div>
                  <dt className="text-xs font-medium tracking-[0.18em] text-foreground/40 uppercase">
                    {t('contact.follow')}
                  </dt>
                  <dd className="mt-2 flex flex-wrap gap-x-6 gap-y-2">
                    {socialMediaLinks.map((social) => (
                      <CloseLink
                        key={social.label}
                        href={social.to}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex min-h-11 items-center gap-1 text-base underline-offset-4 hover:underline"
                      >
                        {social.label}
                        <span aria-hidden="true">↗</span>
                      </CloseLink>
                    ))}
                  </dd>
                </div>
              </dl>
              <div className="mt-6 flex items-center justify-between gap-6 border-t border-border-dark pt-6">
                <p className="text-xs font-medium tracking-[0.18em] text-foreground/40 uppercase">
                  {t('nav.language')}
                </p>
                {languages}
              </div>
            </div>
          </div>
        </Dialog.Popup>
      </Dialog.Portal>
    </Dialog.Root>
  )
}

export default MobileNavigation
